### ISSUE TITLE
Replace uses of undefined with error

### ISSUE THREAD

**Issue by expipiplus1** [clash-lang/clash-prelude#58]
It would be handy to know where an undefined value is coming from when running CLaSH dependent code through GHC.

Replacing uses of `undefined` with `error "Some helpful string"` would be very helpful.

**Comment by christiaanb** [comment]
I agree, I want to use: https://github.com/clash-lang/clash-prelude/wiki/Clock-and-reset-modelling#212-catching-undefined to replace many (probably all) uses of `undefined`.

**Comment by expipiplus1** [comment]
ooh, `errorX` looks very useful, thanks!
