### ISSUE TITLE
Lens.Ixed instance for (Vec n) is not total

### ISSUE THREAD

**Issue by ggreif** [clash-lang/clash-prelude#61]
I am looking at https://github.com/clash-lang/clash-prelude/blob/master/src/CLaSH/Sized/Vector.hs#L1817; consider:
``` haskell
test :: Vec 400 Bool
test = repeat True
el = test ^? ix 401
```
I get:
``` haskell
λ> el
Just *** Exception: CLaSH.Sized.Vector.(!!): index 401 is larger than maximum index 399
```

A possible fix would be to `Lens.Index` be defined as `CLaSH.Prelude.Index n`instead of `Int`. Or make a range check and return `Nothing`.

**Comment by christiaanb** [comment]
Using `Index n` won't help you there, as you get a runtime error for `fromInteger 401 :: Index n`. Bounds checking will add overhead in the generated circuit.
