### ISSUE TITLE
Package name "CLaSH" is a disaster to type

### ISSUE THREAD

**Issue by firegurafiku** [clash-lang/clash-prelude#76]
The «two caps — small letter — two caps» is so unusual pattern, so I just cannot type it automatically, I need to fix my attention to that ridiculous casing. What's wrong with plain «Clash»?

**Comment by christiaanb** [comment]
Well, it all started with "CAES Language for Synchronous Hardware", CLaSH, as the name for the language/compiler. I never gave it much thought when I made the root-name of the module structure the same name as the name of the language/compiler.

**Comment by tomjaguarpaw** [comment]
I'd really appreciate changing the top level module to `Clash`.  I know it's an unwieldy change, but better now than later, and it can be done in a backwards compatible way.

**Comment by christiaanb** [comment]
I'm inclined to do this for the clash 1.0 release, although I can be convinced to do it for the upcoming clash-0.7 release if people really want it.

**Comment by expipiplus1** [comment]
I never had a problem with this, but now every time I type `CLaSH` I think "Oh, I'm experiencing issue #76".

**Comment by expipiplus1** [comment]
Also, why is the lambda lowercase if it's standing for "Language"?

**Comment by christiaanb** [comment]
because the uppercase lambda isn't as cool
