### ISSUE TITLE
Could we have 'Maybe (addr, a)' for asyncFifoSynchronizer too?

### ISSUE THREAD

**Issue by tomjaguarpaw** [clash-lang/clash-prelude#78]
You made a good improvement to `blockRam` here

https://github.com/clash-lang/clash-prelude/commit/dd5d6d6498b3041e8353db582466171fd96bac3d#diff-7d38ffc682830b8659330a410dbf0986R712

making it take a `Maybe (addr, a)` instead of an `addr`, `a`, and `Bool`.  Could we have the corresponding improvement to `asyncFIFOSynchronizer`?

https://github.com/clash-lang/clash-prelude/blob/master/src/CLaSH/Prelude/Synchronizer.hs#L138

**Comment by christiaanb** [comment]
Yes, I'll do so soon.

**Comment by christiaanb** [comment]
`asyncFIFOSynchronizer` has a `Maybe a` a type as its write/push argument as of clash-prelude-0.11
