### ISSUE TITLE
Add Medvedev-style machine?

### ISSUE THREAD

**Issue by ggreif** [clash-lang/clash-prelude#80]
https://en.wikipedia.org/wiki/Finite-state_machine#Hardware_applications

It is just a Moore machine without any output logic:
``` haskell
medvedev transfer start = moore transfer id start
```
But it comes up often, so it is probably a worthwhile  addition.

**Comment by ggreif** [comment]
Should I come up with a pull request?

**Comment by christiaanb** [comment]
Yes, submit a PR please. the `Moore` module is probably the best place for it.

**Comment by ggreif** [comment]
Okay, see PR #81
